# Generated by Django 4.2.8 on 2024-03-02 20:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('meals', '0001_initial'), ('meals', '0002_dish_rename_glucose_glucosemeasurement_and_more'), ('meals', '0003_alter_dish_desc'), ('meals', '0004_alter_glucosemeasurement_options_and_more'), ('meals', '0005_alter_glucosemeasurement_options_and_more'), ('meals', '0006_alter_glucosemeasurement_when_and_more'), ('meals', '0007_meal_appx_alter_insulindelivery_duration')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200, unique=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='GlucoseMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('when', models.DateTimeField(unique=True, verbose_name='Date/Time')),
            ],
            options={
                'ordering': ['when'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(verbose_name='Time meal started')),
                ('dish', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='meals.dish')),
                ('appx', models.BooleanField(default=False, verbose_name='Meal time is approximate')),
            ],
        ),
        migrations.CreateModel(
            name='InsulinDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Insulin units')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='Duration')),
                ('when', models.DateTimeField(unique=True, verbose_name='Date/Time')),
            ],
            options={
                'ordering': ['when'],
            },
        ),
    ]
